### ISSUE TITLE
MasterCard issue

### ISSUE THREAD

**Issue by laymon** [binlist/binlist-data#147]
I have tried several mastercard numbers, debit, debit-prepaid & credit none of them seem to return a length or luhn?

**Comment by tjconcept** [comment]
Hi @laymon,

Thanks for reaching out. That's most surely because you either inputtet too few digits to narrow down the search, or because the resulting range has cards of different length and with and without LUHN.

Some ranges intersect and are only separated by the length of the card, e.g. you have to know the length to get to the precise range.

If you use the API, you can search with the length as well:

```sh
curl -H "Accept-Version: 3" "https://lookup.binlist.net/45717360?number\[length\]=16"
```
